// Copyright 2026 Mark Kimberly Howe. Licensed under the MIT License.

let Workset := {
    "../../../STreuthWorkspace/src/lib/fsm/FSMProtocols.st",
    "../../../STreuthWorkspace/src/lib/fsm/FSMDescription.st",
    "../../../STreuthWorkspace/src/lib/fsm/State.st",
    "../../../STreuthWorkspace/src/lib/fsm/Transition.st",
    "../../../STreuthWorkspace/src/lib/fsm/FSM.st",
    "../../../STreuthWorkspace/src/projects/keymap_chord_builder/ChordBuildDefines.st",
    "../../../STreuthWorkspace/src/projects/keymap_chord_builder/ChordBuilder.st",
    "../../../STreuthWorkspace/src/projects/keymap_chord_builder/ChordBuilderFSM.st",
    "../../../STreuthWorkspace/src/projects/keymap/SemanticKeymap.st",
    "../../../STreuthWorkspace/src/projects/keymap/Keymap.st",
    "Main.st"
}
