// Copyright 2026 Mark Kimberly Howe. Licensed under the MIT License.

let Workset := {
    "../../../STreuthWorkspace/src/lib/html",
    "../../../STreuthWorkspace/src/lib/fsm/FSMProtocols.st",
    "../../../STreuthWorkspace/src/lib/fsm/FSMDescription.st",
    "../../../STreuthWorkspace/src/lib/fsm/State.st",
    "../../../STreuthWorkspace/src/lib/fsm/Transition.st",
    "../../../STreuthWorkspace/src/lib/fsm/FSM.st",
    "../../../STreuthWorkspace/src/lib/fsm/FSMInputView.st",
    "../../../STreuthWorkspace/src/lib/fsm/FsmHTMLDsl.st",
    "Main.st"
}
